### PR TITLE
Safer status write

### PR DESCRIPTION
**Pull request by jcrugzz**
## Summary

Make a retryable stream and handle errors so things dont potentially go wrong if there are sketchy network conditions in talking to nsq.

## Changelog

* Make retryable write-stream for writing with status-writer

### CODE REVIEW

**Review by indexzero — APPROVED** [review]
Unit tests here would be prudent. Okay with a backfill issue if we address it soon.

**Review by msluther — APPROVED** [review]
Should the retryable nsq stream be a separate package?  I suspect we'll need it in [`carpenterd-worker`](https://github.com/godaddy/carpenterd-worker/blob/e4bdf199fd70cd071d5250a7c25e8b0e0690a30f/writer.js#L2) as well.

**Comment by jcrugzz** [comment]
@msluther yea this is just the initial pathway to get it deployed and then go through the process to do that.

**Comment by jcrugzz** [comment]
@indexzero yea tests will come when its made a separate package

**Comment by jcrugzz** [comment]
travis isnt working for cassandra for some rason :(. I sent a message to support so hopefully this will be resolved.

**Pull request merged**
